name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/
      - run: npm run bootstrap
      - run: npm run build
      - run: node scripts/bump-version.js
      - run: |
          VERSION=$(node -p "require('./lerna.json').version")
          gh auth setup-git
          git config --global user.name 'Release'
          git config --global user.email 'release@bot.com'
          git checkout -b "bump-version-$VERSION"
          git commit -am "chore: Bump version ($VERSION)"
          git push --set-upstream origin "bump-version-$VERSION"
          PR_URL="$(gh pr create --title "chore: Bump version ($VERSION)" --body 'This is automatic PR to bump version')"
          gh pr merge --admin --squash "$PR_URL"
          gh release create "$VERSION" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${VERSION#v}" \
            --generate-notes \
            ./lib/*.zip
        env:
          GH_TOKEN: ${{ github.token }}
